2024-02-24 10:36:34,143 ERROR: Exception on /register [GET] [in /mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/routes.py", line 106, in register
    return render_template('register.html', title='Register', form=form)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/templates/register.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/templates/base.html", line 52, in top-level template code
    {% block content %}
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/templates/register.html", line 30, in block 'content'
    {% for error in password.errors %}
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'password' is undefined
2024-02-24 10:36:36,573 ERROR: Exception on /register [GET] [in /mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/routes.py", line 106, in register
    return render_template('register.html', title='Register', form=form)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/templates/register.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/templates/base.html", line 52, in top-level template code
    {% block content %}
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/templates/register.html", line 30, in block 'content'
    {% for error in password.errors %}
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'password' is undefined
2024-02-24 10:36:47,887 ERROR: Exception on /register [GET] [in /mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/routes.py", line 106, in register
    return render_template('register.html', title='Register', form=form)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/templates/register.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/templates/base.html", line 52, in top-level template code
    {% block content %}
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/project-workthrough/app/templates/register.html", line 30, in block 'content'
    {% for error in form.username.errors %}
  File "/mnt/c/Users/ayand/OneDrive/Documents/software_development/chapter9_assessment_project/ball/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'password' is undefined
